# Generated by Django 5.0 on 2023-12-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_tracking', '0002_alter_purchaseorder_delivery_date'),
        ('vendor_profile_management', '0002_rename_on_time_delivery_date_vendor_on_time_delivery_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vendor_profile_management.vendor'),
        ),
    ]
