# Generated by Django 5.0 on 2023-12-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_profile_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='on_time_delivery_date',
            new_name='on_time_delivery_rate',
        ),
    ]
